### ISSUE TITLE
incorrect escaping of root folder path

### ISSUE THREAD

**Issue by dennisbaum** [Amaimersion/remove-files-webpack-plugin#16] opened 2020-01-14 13:22 UTC
Hi Sergey, 
i like to remove a file after compilation, but unfortunately that does not work,
the file is skipped, because unsafe.
i have possibly a problem with the formatting of the root parameter.
the comparison in the isSave-Method results in false.

macOS: Mojave, 10.14.6
webpack: 4.41.5
remove-files-plugin: 1.2.1

i changed your simple example

![image](https://user-images.githubusercontent.com/562826/72353024-9e53f580-36e3-11ea-9d7f-a4f89f28fb93.png)

to:

```js
new RemovePlugin({
    after: {
        root: './dist',
        include: [
            'test.js',
            'test2.js'
        ],
        logDebug: true
    }
})
```

results in:
```
remove-files-plugin@1.2.1:
Skipped, because unsafe removing – "dist/test.js"
Skipped, because not exists – "dist/test2.js"
An items for removing in trash not found

remove-files-plugin@1.2.1:
Hook started – "afterEmit"
"test.js" converted to "dist/test.js"
"test2.js" converted to "dist/test2.js"
Testing skipped, because params.test is empty
Before formatting:
Root – "./dist"
Path – "dist/test.js"
After formatting:
Root – "\\/Users\\/dennisbaum\\/Projects\\/test_remove_files\\/dist"
Path – "/Users/dennisbaum/Projects/test_remove_files/dist"
Save – "false"
Skipped, because unsafe removing – "dist/test.js"
Skipped, because not exists – "dist/test2.js"
Directories before cropping – 
Files before cropping – 
Directories after cropping – 
Files after cropping – 
An items for removing in trash not found
Hook ended – "afterEmit"
```

The escaped root param looks different, and i don't know if the filename should be part of Path?
However, after formatting the comparison is not safe
```
After formatting:
Root – "\\/Users\\/dennisbaum\\/Projects\\/test_remove_files\\/dist"
Path – "/Users/dennisbaum/Projects/test_remove_files/dist"
Save – "false"
```

It works if i don't escape the root in plugin.js, but i don't know the consequences for other OSes...
```js
//const rootFormat = format(root, true, true);
const rootFormat = format(root, false, true);
const pthFormat = format(pth, false, true); // we shouldn't escape.
```

As a workaround i use allowRootAndOutside: false, because then no formatting occurs, but i think that is not the best solution...

Any idea how that could be working?
Tnx.

**Comment by Amaimersion** [comment] 2020-01-15 16:57
Hello!

Thank you for detailed description. Let me some time to test this on unix systems, because on Windows it is works fine.

Similar issues:
https://github.com/Amaimersion/remove-files-webpack-plugin/issues/15

**Comment by imachug** [comment] 2020-01-16 20:07
Quickly jumping in because I have a similar problem. I'm using the plugin on Linux like this:

```javascript
...
		new RemovePlugin({
			before: {
				include: ["main/dist"],
				exclude: ["main/dist/data"]
			}
		}),
...
```

I get the following error:

```
Skipped, because unsafe removing – "/home/ivanq/Documents/[censored]/main/dist"
An items for removing in trash not found
```

The root is `/home/ivanq/Documents/[censored]`.

The issue seems to be connected with isSave function: `/home/ivanq/Documents/[censored]` isn't changed while in `/home/ivanq/Documents/[censored]/main/dist` the slashes are replaced with `\\\\/`. I think swapping `if (escape) {` and `if (replaceDoubleSlash) {` should work, I haven't tested this on Windows though.

**Comment by dennisbaum** [comment] 2020-01-17 17:28
@imachug does your [censored] part contains a minus or other special characters? 
"/home/ivanq/Documents/**test-project**/main/dist"

On the windows-machine from my colleague, that doesn't work in that case
Skipped, because unsafe removing...
If he changes to **testproject** it works. 

on the macos, that doesn't work either.

**Comment by imachug** [comment] 2020-01-18 04:12
It doesn't, just alphanumeric symbols.

**Comment by Amaimersion** [comment] 2020-01-19 13:56
Good day @dennisbaum and @imachug!

First of all, thank you for detailed description.
Secondly, sorry for late response. I have a work and because of this i don't have much free time to fix this issue quickly.

## Why it not works as expected

Let me clarify some things.

>and i don't know if the filename should be part of Path?

No, it shouldn't be. What you see it is intended behavior.

The issue is connected with incorrect escaping. In particular, in this piece of code:
```javascript
// escapes any of this characters: - [ ] / { } ( ) * + ? . \ ^ $ |
// example: "-" -> "\\-"
return string.replace(
    /[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,
    '\\$&'
);
```
As you already seen plugin does escaping of root, but doesn't do that for file/folder path. There is many reasons why i implemented this behavior, but it is big mistake because i made no provision of many things.

So: 
- on POSIX systems it is not works because of unnecessary escaping of `/`;
- on Windows systems it is not works because of `- [ ] / { } ( ) * + ? . \ ^ $ |` characters in a root.

It wasn't a problem earlier (if i tested it right), but in 1.2.x i cardinally changed `isSave` method and because of these mistakes `isSave` started behaved incorrectly.

Sorry for that. That will be fixed in future version. I will try to release this as soon as possible.

## Temporary fixes at the moment

### Windows systems

- remove all of this characters (`- [ ] / { } ( ) * + ? . \ ^ $ |` ) from the root folder name;
- or set `allowRootAndOutside: true`;
- or downgrade to `1.1.x` versions.

### POSIX systems

- set `allowRootAndOutside: true`;
- or downgrade to `1.1.x` versions.

**Comment by dennisbaum** [comment] 2020-01-19 14:41
> I have a work and because of this i don't have much free time to fix this issue quickly.

i think anyone knows that. no worries and thank you for this plugin and the fast response!
as you said and i already do: as a workaround i use allowRootAndOutside: true;
as long as i remove only known files, that wouldn't be a prob.
Cheers Sergey

**Comment by Amaimersion** [comment] 2020-01-19 16:28
The issue should be resolved. Please upgrade to 1.2.2 version. Feel free to reopen this if something will go wrong.

**Closed by Amaimersion** 2020-01-19 16:29 UTC
Labels: bug
